spring:
  application:
    name: config
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

build:
  id: ${ID}
  version: ${VERSION}
  name: ${NAME}


# BUILD_ID=4444; BUILD_NAME=NAME_TEST; BUILD_VERSION=1.0.0

management:
  endpoints:
    web:
      exposure:
        include: refresh


server:
  port: 8084