spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3309/ecomapp_product_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000 # 30 sec
      max-lifetime: 1800000 # 30 min
      connection-timeout: 20000 # 20 sec
      pool-name: MyHikariCP
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8081