spring:
  application:
    name: ecom-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\Dublin\Interview Prep\Microservices\E-Commerce-Microservices-App\ecom-config-server\src\main\resources\config

  #RabbitMQ Configs
  #RabbitMQ Configs
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888